/**
 * Auditi strukture (naslovi, razmaci odlomaka, prva stranica, TOC) izvuceni iz monolita,
 * korak 4 porta enginea. Tijela prepisana 1:1 iz monolita pa golden snapshoti ostaju
 * nepromijenjeni.
 *
 * Tipizirano na granici (`: any` za OOXML cvorove i inline callbacke), bez promjene
 * ponasanja; golden snapshoti ostaju nepromijenjeni.
 */
// Eksplicitne .ts ekstenzije: u Deno grafu Academic Core sava (evaluateZeroParagraphSpacing).
import { normalize, sectionName } from '../utils/helpers.ts';
import { makeCheck, issue } from '../scoring/checks.ts';
import { runMetrics, headingNumberInfo, isUppercaseText, isFrontMatterHeading, near } from './metrics.ts';

/**
 * Oblikovanje naslova po razinama (6 bodova). Podrzava `rules.levels[N].{uppercase,bold,italic}` i
 * velicinu.
 *
 * VELICINA PO RAZINI dodana 2026-08-24. Dotad je `rules.size` bila JEDNA vrijednost za sve razine,
 * pa izvor koji propisuje stepenicu (vuka: glave 16, poglavlja 14, potpoglavlja 12) nije imao cime
 * to izraziti. `expected.size` ima prednost pred `rules.size`; profil koji ni jedno ne postavlja
 * ostaje netaknut, pa golden ne mice.
 */
export function auditHeadingRules(headings: any, rules: any): any{const candidates=headings.filter((h: any)=>h.headingLevel&&h.headingLevel<=Number(rules.maxLevel||9)&&!isFrontMatterHeading(h.text));if(!candidates.length)return[makeCheck('structure','Oblikovanje naslova po razinama','warn',0,0,'Nema dovoljno Heading/Naslov odlomaka za detaljnu provjeru')];const formatBad=[],numberBad=[],alignBad=[];for(const h of candidates){const expected=(rules.levels||{})[String(h.headingLevel)]||{},meta=runMetrics(h.runs),num=headingNumberInfo(h.text),autoNumber=!!h.pProps.num;const _wantSize=expected.size??rules.size,sizeOk=!_wantSize||!meta.size||near(meta.size,_wantSize,.15),upperOk=!expected.uppercase||isUppercaseText(h.text),boldOk=!expected.bold||meta.boldShare>=.65,italicOk=!expected.italic||meta.italicShare>=.65;if(!(sizeOk&&upperOk&&boldOk&&italicOk))formatBad.push({h,meta,expected});const numberExists=!rules.numberRequired||!!num||autoNumber,depthOk=!num||num.depth===h.headingLevel||(num.roman&&h.headingLevel===1&&rules.romanLevelOneAllowed),romanOk=!num||!num.roman||h.headingLevel===1&&rules.romanLevelOneAllowed,dotOk=!rules.trailingDot||!num||num.trailingDot;if(!(numberExists&&depthOk&&romanOk&&dotOk))numberBad.push(h);const a=h.pProps.align;if(a&&!['left','start'].includes(a))alignBad.push(h)}const fOk=!formatBad.length,nOk=!numberBad.length,aOk=!alignBad.length;return[makeCheck('structure','Oblikovanje naslova po razinama',fOk?'pass':'warn',fOk?6:Math.max(1,6-formatBad.length),6,fOk?`${candidates.length} naslova odgovara profilnim pravilima veličine i isticanja`:`${formatBad.length} od ${candidates.length} naslova odstupa od očekivanog velikog slova/bold/italic obrasca`,fOk?null:issue('warning','structure','Naslovi ne prate profil razina',formatBad.slice(0,7).map((x: any)=>`odlomak ${x.h.index}: ${x.h.text.slice(0,70)}`).join('; '),'Naslovi')),makeCheck('structure','Numeriranje naslova',nOk?'pass':'warn',nOk?4:Math.max(1,4-numberBad.length),4,nOk?'Prepoznato je dosljedno numeriranje u skladu s razinom naslova':`${numberBad.length} naslova nema odgovarajuću oznaku razine ili završnu točku`,nOk?null:issue('warning','structure','Numeriranje naslova nije dosljedno',numberBad.slice(0,7).map((h: any)=>`odlomak ${h.index}: ${h.text.slice(0,70)}`).join('; '),'Naslovi')),makeCheck('structure','Poravnanje naslova slijeva',aOk?'pass':'warn',aOk?3:1,3,aOk?'Nisu pronađeni naslovi izričito poravnani drugačije od lijevog ruba':`${alignBad.length} naslova izričito je poravnano drugačije`,aOk?null:issue('warning','structure','Naslovi nisu poravnani slijeva',alignBad.slice(0,7).map((h: any)=>`odlomak ${h.index}: ${h.text.slice(0,55)}`).join('; '),'Naslovi'))]}
// Faza D (cisti sav): mjerenje i evaluacija razmaka su razdvojeni. measure trosi
// odlomke (tekst mu treba samo za length filter), a u mjerenje ulaze ISKLJUCIVO
// indeksi i pt vrijednosti; evaluate je cista (measurement, label) -> Check i moze
// zivjeti bez odlomaka (buduci Academic Core). Stari export je kompozicija.
export function measureZeroParagraphSpacing(paragraphs: any): import('../scoring/evaluate/measurements.ts').ZeroSpacingMeasurement{const candidates=paragraphs.filter((p: any)=>p.text&&p.text.length>15&&!p.headingLevel&&!/^(?:toc|sadrzaj)\s*\d*/i.test(p.styleName||'')),known=candidates.filter((p: any)=>p.pProps.before!=null||p.pProps.after!=null),bad=known.filter((p: any)=>Math.abs(Number(p.pProps.before||0))>.6||Math.abs(Number(p.pProps.after||0))>.6);return{knownCount:known.length,badCount:bad.length,badSamples:bad.slice(0,8).map((p: any)=>({index:p.index||'fusnota',before:p.pProps.before??null,after:p.pProps.after??null}))}}
export function evaluateZeroParagraphSpacing(m: import('../scoring/evaluate/measurements.ts').ZeroSpacingMeasurement, label: any, category: any='formatting'): any{if(!m.knownCount)return makeCheck(category,label,'pass',3,3,'Razmak prije/poslije nije izričito zapisan u analiziranim stilovima; nema bodovnog kažnjavanja');const ok=!m.badCount,share=m.knownCount?Math.round(m.badCount/m.knownCount*100):0;return makeCheck(category,label,ok?'pass':'warn',ok?3:Math.max(1,3-m.badCount/5),3,ok?`${m.knownCount} provjerljivih odlomaka ima razmak 0 prije i poslije`:`${m.badCount} od ${m.knownCount} provjerljivih odlomaka odstupa (${share}%)`,ok?null:issue('warning',category,`${label} nije postavljen na 0`,m.badSamples.map((s)=>`odlomak ${s.index}: prije ${s.before??'?'} pt / poslije ${s.after??'?'} pt`).join('; '),label))}
export function auditZeroParagraphSpacing(paragraphs: any, label: any, category: any='formatting'): any{return evaluateZeroParagraphSpacing(measureZeroParagraphSpacing(paragraphs),label,category)}
export function firstPageParagraphs(paragraphs: any): any{const out: any=[];let nonempty=0,confident=false;for(const p of paragraphs){out.push(p);if(p.text)nonempty++;if(p.pageBreakAfter&&nonempty>=2){confident=true;break}if(out.length>=55)break}out.confident=confident;return out}
export function tocEntryParagraphs(paragraphs: any): any{const styled=paragraphs.filter((p: any)=>/^(?:toc|sadrzaj)\s*[1-9]$/i.test(String(p.styleName||'').trim())||/^(?:toc|sadrzaj)[1-9]$/i.test(normalize(p.styleName||'')));if(styled.length)return styled;const start=paragraphs.findIndex((p: any)=>['sadrzaj','contents','tableofcontents'].includes(sectionName(p.text)));if(start<0)return[];const out=[];for(let i=start+1;i<Math.min(paragraphs.length,start+100);i++){const p=paragraphs[i];if(p.headingLevel&&!/^(?:toc|sadrzaj)/i.test(p.styleName||''))break;if(p.text&&(/\t\s*\d+\s*$/.test(p.text)||/\s\d+\s*$/.test(p.text))&&p.text.length<250)out.push(p)}return out}
